# This is a basic workflow to help you get started with Actions

name: angular-co2-footprint-CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Node js 
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

    # npm install
      - name: npm install
        run: npm install

    # build
      - name: build
        run: npm run build -- --configuration production
    
    # test
      - name: test
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
          
              
