# This is a basic workflow to help you get started with Actions

name: angular-co2-footprint-deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Node js 
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

    # npm install
      - name: npm install
        run: npm install

    # build
      - name: build
        run: npm run build -- --configuration production --base-href "/angular-co2-footprint/"
    
    # Upload
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Artifact name
          name: github-pages # optional, default is github-pages
          # Path of the directory containing the static assets.
          path: dist/angular-demo/browser # default is _site/
          
  deploy:
    # Add a dependency to the build job
    needs: build
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: github-pages # optional, default is github-pages
          
              
